Description: Base System
Name: base
Packages:
- alsa-utils
- audio-session-manager
- bash
- binutils
- bluetooth-frwk
- bluetooth-frwk-agent
- bluez
- bluez-gstreamer
- bzip2
- ca-certificates
- cert-svc
- connman
- coreutils
- cpio
- dlogutil
- drm-service
- e2fsprogs
- filesystem
- gawk
- grep
- gzip
- insserv
- less
- libsqlfs
- libss-client
- login
- lsb
- mingetty
- mkdevnodes
- module-init-tools
- mtdev
- net-tools
- ofono
- passwd
- prelink
- procps
- psmisc
- readline
- rfkill
- rpm
- sed
- sensor-framework
- setup
- sonet
- ss-server
- sysvinit
- sysvinit-utils
- tar
- tizen-release
- tizen-repos
- tzdata-slp
- udev
- usbutils
- util-linux-ng
Summary: Base System
